# Generated by Django 2.0.5 on 2018-11-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
